### PR TITLE
why cant i close the app

### PR DESCRIPTION
**Pull request by idkkkkjk**
idk this stuff but this app wont let me close it i hate it so much plz help

### CODE REVIEW

**Comment by Simran-B** [comment]
Do not abuse pull requests for support requests. Ask for help on the Discord server: https://discordapp.com/invite/4Ae9KZn

**Comment by idkkkkjk** [comment]
whats that

**Comment by idkkkkjk** [comment]
no ones helping

**Comment by sobotka** [comment]
Stop fucking posting here shithead.

**Comment by idkkkkjk** [comment]
no
i will keep makiing them

**Comment by idkkkkjk** [comment]
and if somthing happends i will make a new account

**Comment by idkkkkjk** [comment]
> Stop fucking posting here shithead.

no i will keep making new ones until my problem is solved

**Pull request closed without merging**
