### PR TITLE
Bring back old translations and update them

### PR DESCRIPTION
**Pull request by prokoudine**
Old translation are automatically marked as fuzzy, so they only need to be confirmed where applicable. This should be a good start instead of forcing people to do it all over again :)

### CODE REVIEW

**Comment by Simran-B** [comment]
Wouldn't it be better to keep obsolete translations until someone checked whether they can be matched up with new translatable strings?

For example, "Project Save As..." was apparently changed to "Project Save As". The former had a translation in 0.1 in the file `ar_AR.ts` ( أحفظ المشروع ك...) but this PR only has the source string and no translation. It would only be a matter of removing `...`, for which you don't even need to know the language.

**Comment by prokoudine** [comment]
I can't confirm that. The translation _is_ present here. Anyway, this is not how lupdate works. Before marking something as obsolete, it tries to find closest looking matches, inserts them, and marks as fuzzy. Then it removes obsoletes.

image

**Comment by elsandosgrande** [comment]
I was about to say that looking at the `.ts` files alone probably doesn't paint the whole picture. I'll see how things stand with my translations and Qt Linguist and report back, but this pull request seems fine to me for now.

**Comment by Simran-B** [comment]
My bad, it's `Save Project &amp;As` now. That didn't show up in my quick search. Should be fine fine.

**Comment by elsandosgrande** [comment]
As far as Bosnian and Serbian go, everything's fine.

**Review by elsandosgrande — APPROVED** [review]

**Review by Simran-B — APPROVED** [review]

**Pull request merged**
