### PR TITLE
add cmake buildsystem

### PR DESCRIPTION
**Pull request by eszlari**
advantages:
* easy to add new dependencies(+checking)
* fast with ninja back-end (`cmake -G Ninja`): https://ninja-build.org
* a lot of tools support it much better than qmake
* Qt 6 will be using cmake: https://lists.qt-project.org/pipermail/development/2018-October/034023.html
* clang-tidy integration: https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CLANG_TIDY.html

### CODE REVIEW

**Comment by eszlari** [comment]
I have only tested this on Linux so far.

**Comment by DeveloperPaul123** [comment]
I can test this out on windows, but just looking at the CMakeLists I would suggest not using `PkgConfig` for windows. Something like `vcpkg` would play nicer on windows with cmake. Especially with visual studio.

@eszlari Just curious but what distribution of Linux did you test this on?

**Comment by itsmattkc** [comment]
`pkgconfig` would work if the user is compiling with MinGW. Perhaps have an option for that or `vcpkg` (and/or automatically check whether the build environment is MinGW or MSVC).

**Comment by eszlari** [comment]
> but just looking at the CMakeLists I would suggest not using PkgConfig for windows.

I removed pkgconfig usage.

> Just curious but what distribution of Linux did you test this on?

Kubuntu 18.10

**Comment by DeveloperPaul123** [comment]
@eszlari I had to make some minor changes to allow for compilation to work. I also had to make a minor code change to fix a compilation error regarding the use of `LoadLibrary()` on windows. Should I create a PR to your `cmake` branch or just commit them to the existing branch you have?

**Comment by eszlari** [comment]
I would open a PR against upstream for the compile fix  and a PR against my cmake branch for your MSVC support.

**Comment by DeveloperPaul123** [comment]
@eszlari Ok will do

**Comment by DeveloperPaul123** [comment]
@eszlari I filed a PR against your `cmake` branch.

**Comment by DeveloperPaul123** [comment]
Is there any desire to add installation support and possible installer generation support via CPack?

**Comment by eszlari** [comment]
@itsmattkc This is more or less ready from my side, any comments?

**Comment by eszlari** [comment]
Small speed comparison:

qmake+make:
```
real    1m0,535s
user    7m21,124s
sys     0m27,312s
```
cmake+ninja:
```
real    0m35,959s
user    4m6,466s
sys     0m15,528s
```

**Comment by itsmattkc** [comment]
Very interesting, give me some time to test it properly and I'll get back to you within a few days

**Comment by DeveloperPaul123** [comment]
Since this is taking some time to merge I'd like to propose adding in auto building (if needed) of some of the optional dependencies of olive to take full advantage of CMake.

Specifically I had `frei0r` and `OpenColorIO` in mind. Thoughts?

**Comment by itsmattkc** [comment]
Apologies for the late merge, everything seems good.

Auto-building may be good one day for OpenColorIO, availability for it seems to vary a lot per platform/distribution. Don't bother with Frei0r though, [it's getting phased out](https://github.com/olive-editor/olive/wiki/Frei0r-Support-EOL) and either way doesn't really need to be built for Olive, it only requires including `frei0r.h` to compile support in.

**Comment by DeveloperPaul123** [comment]
Sounds good, a PR for OpenColorIO would be relatively easy to do. Another option is to build OpenColorIO as part of `olive` using CMake's [`FetchContent`](https://cmake.org/cmake/help/v3.11/module/FetchContent.html) as opposed to [`ExternalProject`](https://cmake.org/cmake/help/v3.11/module/ExternalProject.html?highlight=externalproject). Is there a preference?

**Comment by sobotka** [comment]
Chaining #826 into this.

**Pull request merged**
