### PR TITLE
lupdate and german translation update

### PR DESCRIPTION
**Pull request by naj59**

### CODE REVIEW

**Comment by itsmattkc** [comment]
Hi thanks for the update, but could you restrict your PR to only the updated German translation? Updating the other TS files in the repository could cause merge issues if anyone else is working on one of them locally.

**Comment by naj59** [comment]
Problem at this point is that without ``lupdate`` it refers to the old source points where no translation is going to be found.

**Comment by itsmattkc** [comment]
Is that the case with the resulting `.qm` files?

**Comment by naj59** [comment]
I don't understand this concretly. Without updating the ``.ts`` files old strings are "not used anymore". This would probably resist in a non-translated ui.

**Comment by itsmattkc** [comment]
I suppose if anyone's having merge issues, they can just override the repo's version with theirs.

**Pull request merged**
