### PR TITLE
Preliminary Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
This makes it run on Haiku, although it crashes on exit and can't use OpenGL yet.
I think some ifdefs could use some cleanup, like qmake should pass a HAVE_DLOPEN or something instead.

### CODE REVIEW

**Comment by mmuman** [comment]
[Looks good](https://twitter.com/mmu_man/status/1102293229381271552) at least.

**Comment by elsandosgrande** [comment]
Well, good luck with adding support! I wonder if this makes Olive Haiku's first ever video editor.

**Comment by mmuman** [comment]
No, we do have some native apps, but someone mentioned it on our forum, so I had a try.

**Comment by itsmattkc** [comment]
That's a shame Haiku doesn't have QtOpenGL yet, but it's great seeing Olive running on a new OS!

**Pull request merged**
