### PR TITLE
GCC Fixes

### PR DESCRIPTION
**Pull request by sobotka**
For the last batch of changes, some minor fixes were required. @itsmattkc should check on the fix for the enum in keyframes, as the kDefaultType was causing linker errors. Not sure if the fix is suitable or if there is a better way to resolve it.

### CODE REVIEW

**Comment by tin2tin** [comment]
Dunno if this is related. Error in the latest build here: https://ci.appveyor.com/project/itsmattkc/olive/build/artifacts 
image

**Comment by tin2tin** [comment]
This one is also missing(at startup):
image

**Comment by tin2tin** [comment]
Apparently those dlls are from this: https://www.msys2.org/

**Comment by sobotka** [comment]
I'm pretty sure AppVeyor and such are still busted. If you can get a local build going, that would be helpful.

**Comment by BrimsonBhin** [comment]
@tin4tin and everyone else on Windows..

Here is a temporary solution. Extract the .dlls from [this 7zip archive](https://github.com/BrimsonBhin/olive_missingDLLs/archive/master.zip) and put it into your `../olive` directory

**Comment by tin2tin** [comment]
Thank you BrimsonBihn. Unfortunately when trying to unzip missinglargedlls.7z with 7z I get this error: 
image

**Comment by BrimsonBhin** [comment]
@tin2tin My apologies, was using 7zip-zstd

Here arethe links for [libopenblas](https://packages.msys2.org/package/mingw-w64-x86_64-openblas) and [libicudt65](https://packages.msys2.org/package/mingw-w64-x86_64-icu)

You should find the dlls in the `bin` subfolders

**Comment by tin2tin** [comment]
Now it is working. Thank you!

**Comment by itsmattkc** [comment]
Thanks for making a PR but I felt it would be best to address all GCC warnings/errors together

**Comment by sobotka** [comment]
It did.;)

**Pull request closed without merging**
