### PR TITLE
Three types of Glitch effect Added

### PR DESCRIPTION
**Pull request by cgvirus**
Hello my first contrib for Effects in Olive. There are 3 types of Glitch effects in distort section.

### CODE REVIEW

**Comment by NathanSalapat** [comment]
I'm a nobody in this project, but you might get better luck with some pictures or explanations of what the glitch effects are. :)

**Comment by BrimsonBhin** [comment]
I do not know if this effect should be in the `distort` category. Distort effects in olive are mathematics that do not tamper with the color of the video. This one enforces some color changes for the aesthetic. Here are the 3 effects

**Signal Loss**
signal loss

**Bad TV**
bad tv

**Worse TV**
worse tv

Is there a way to configure the blockiness and direction of the effect? That would be perfect. If you have way more, I think you can create your own repo for you own custom effects so Olive does not become messy. I would gladly star that repo and link it in the Wiki :).

**Comment by BrimsonBhin** [comment]
This seems to be a port of [this shader form shadertoy](https://www.shadertoy.com/view/lsfGD2).

Unless that Shadertoy account is your's, I would also advise giving credit

**Comment by alcomposer** [comment]
Shader toy may / may not be GPL depended on the license that is associated with the effect. And if so yes the license needs to remain in the shader source.

Either way, effects like this don't need to be added to Olive itself, they can be imported by the user very easily.

**Comment by BrimsonBhin** [comment]
Yup, a separate repository with a README on how to add them would suffice.

**Comment by alcomposer** [comment]
My motivation for pointing this out is that @itsmattkc has already implemented a very advanced GLSL plugin system, and that there could easily be 1,000,000 effects users could want to use. Other software has effects plugins that are not part of the software. (Even NUKE has external OpenFX effects).

**Comment by cgvirus** [comment]
Hi folks Thanks for starting the conversation.

- Licence: I almost forgot about the licence block. When I was learning GLSL these three effects were my part of research and I always start with these to make sure all uniforms are under API compliance. It seems Olive has all Uniform types under the hood and now my template is ready for future.
I will attach the licence block here which are Unlicensed and GPL. Will link them in the block.

- Category: I agree with the point of Distort. I think a dedicated GPU Effect section would be better.

- **Repository:** PLEASE Let me know if this can be done! I am searching for it! If we can only add this effects by Olive preference path or somehow then I don't have to push/pull and wait for Olive to be build (Which can become pretty huge BTW). I can control my decisions and corrections too. And Worldwide contribs can merge there effects easily as well. 
How can we do it specially with Appimage? I have some of my shaders and vert scripts and the good thing is Olive already supports a pretty huge GLSL arena. So there is a huge area Olive can cover itself.

I am glad the conversation has began. The earlier is the better.
Let me know folks!

@alcomposer @BrimsonBhin @itsmattkc

**Comment by alcomposer** [comment]
At this stage it could be as simple as hosting your effects in your own repository on GitHub. N need to have the rest of Olive there, but have a dedicated repo for your effects.

Currently there are many huge changes happening to Olive, least of which is transitioning to OCIO color management, and using Scene Linear working space. This will effect GLSL effects that deal with color, as they will need to be able to accept, and output in scene linear. Any sort of effect that needs to invert the color values for example (1-c) will fail, as scene linear is not clamped from a 0<1 range.

As @BrimsonBhin has pointed out, having a folder, with a readme at this point would enable users to work out how to use the GLSL filters.

Remember that as Olive is still very young, and currently going though huge changes, there may be further changes to come in the effects infrastructure. IIRC @itsmattkc has needed to move to a new OpenGL version to allow OCIO integration. He probably would be the best to comment on that.

Other than that, that you for making these GLSL effects work with Olive, and I hope to see more in the future!  :+1:

**Comment by cgvirus** [comment]
@alcomposer Alright, So if I create a repo with effects/shader folder then how can users (I mean average users) can install them?

Currently I am doing it by building Olive in my Debian box. As appimage has some issue #698

Here I have found a folder effects/shader. And I am following the xml to load it.

Please let me know. Thanks. 
I would like to promote Olive within this power of GLSL and my audience most of them can't understand complication. I will make a README with this instruction as well. Thanks for your time.

**Comment by alcomposer** [comment]
> Alright, So if I create a repo with effects/shader folder then how can users (I mean average users) can install them?

Depending on your target audience, you could always include a simple installer with your shaders? All it would need to do is know the installed directory of Olive, and then place all the files into the shaders folder? That may work?

**Comment by cgvirus** [comment]
Yes, that may work but Appimage comes only as a single pack. I think if we can have a path option in preference to link the shaders it may work. @alcomposer

**Comment by itsmattkc** [comment]
>Category: I agree with the point of Distort. I think a dedicated GPU Effect section would be better.

Keep in mind that *all* of Olive's effects are GPU effects (with the exception of Frei0r which is currently being phased out) so a "GPU Effect" section is unnecessary. I agree with @BrimsonBhin that "Stylize" is the correct place to put this.

Anyway when it comes to merging these, they look good and I am interested in merging them, but there are certainly concerns regarding licensing and scene linear. I'm not sure how Shadertoy works (i.e. if you need to contact the authors or there's a stock license, etc.) and I see some clamps between 0.0 and 1.0 which may be problematic. They'll have to be tested with the `furtherocio` branch.

**Comment by cgvirus** [comment]
@itsmattkc Thanks. I will update the licence and let you know. But rather than merging can we make a search path system in Olive preference? So that, users can load or write their own shaders and test it. It would also help the devs like us to share at maximum speed with users and also with Olive Team.

**Comment by itsmattkc** [comment]
I'm not really convinced having an extra search path that users have to manage is any easier than just copying files to `/usr/local/share/olive-editor/effects`. A local user path like `~/.local/share/olive-editor/effects` may be a good idea for those without root access though. For developers there is the `OLIVE_EFFECTS_PATH` environment variable which will add an extra search path.

**Comment by cgvirus** [comment]
So what should I say to the users using appimage? I have tried this link copying effects.
`/usr/local/share/olive-editor/effects`
but appimage can't link it. 
Which package user should use in this case as Debian package is too old and buggy.

Let me know please all the links user should copy the effects into (Win, Mac, OSX). I will create a repo only with shaders so that Olive Team can focus on the main app. I will make README with your instructions.

Thanks. 
@itsmattkc

**Comment by cgvirus** [comment]
Hi regarding the topic of path:
issue ##721

**Comment by cgvirus** [comment]
Hi I have created a repo here:
https://github.com/cgvirus/Olive-Editor-Community-Effects

I am closing this merge as the recent changes https://github.com/olive-editor/olive/commit/a581d36bcc830bf81bcb2526596b0d0ff44e7768 is ready for personal contribution.

Please feel free to contribute in this repo and may be this can become a vault for Olive-Editor community. Let me know if you want to join in this repo for some admin privilege as well. I will add more effects soon.

Thanks @BrimsonBhin @alcomposer @itsmattkc

**Comment by cgvirus** [comment]
Also @itsmattkc can we make subcategories through xml? like community>stylized>Glitch? It may become over-flooded soon so a subcategory would be nice I think. Thanks.

**Pull request closed without merging**
