### PR TITLE
Add Clear Disk Cache to Sequence menu

### PR DESCRIPTION
**Pull request by Simran-B**
A faster way to clear disk cache while testing 0.2, see #1305

### CODE REVIEW

**Comment by TheTechRobo** [comment]
What's the status on this PR?

**Comment by Simran-B** [comment]
Well, the intent of this PR is to make it easier to clear the cache. There is a problem however: Olive only deletes the files that it knows are cache files, but in case of a crash it may "forget" about some and thus not erase them. The likelihood of these being corrupted is high, and the can cause follow-up issues, see https://github.com/olive-editor/olive/issues/1284#issuecomment-729136248

So without further changes, this PR doesn't really improve alpha testing. A better cache clearing solution is needed.

**Comment by elsandosgrande** [comment]
Could the cache files have something like an identifier in the file name? If, say, every cache file begins with `olive-editor-cache`, then it should be easy to avoid collisions with other files while being able to easily identify the file.

**Comment by TheTechRobo** [comment]
@elsandosgrande and, on startup it picks a random number for the prefix, and anything that doesn't start with that prefix will be deleted?

**Comment by elsandosgrande** [comment]
@TheTechRobo What do you mean by picking a random number for a prefix? Every cache file would begin with the string `olive-editor-cache` and thus be easily detectable within the designated directory.

**Comment by TheTechRobo** [comment]
I was thinking because that way it wouldn't delete current cache files, but that's invalid since we'd be running that on startup.

So forget what I said. :cat_smile:

**Comment by Simran-B** [comment]
It should clear the entire cache without accidentally deleting user files. There's no need to add a salt to make cached files from different sessions distinguishable.

**Comment by ThomasWilshaw** [comment]
Would it maybe make more sense to give the cache exrs a custom extension like .ovexr or something?

**Comment by sobotka** [comment]
> Would it maybe make more sense to give the cache exrs a custom extension like .ovexr or something?

Ideally there should be a point where external tools can pre-generate the cache files. Having the cache in a well documented and robust file format is an asset.

**Comment by Simran-B** [comment]
What would be the benefit of allowing tools other than Olive to pre-generate the cache? Why not let Olive handle that, e.g. as a headless process that monitors a folder?

The problem is that Olive calculates a hash value for each frame which it uses to organize its mediacache. External tools would have to implement the same logic to place the files where Olive will look for them. The hash algorithm may change, which would break the pipeline. A possible trade-off would be to let external tools create EXRs and have Olive move/copy them into its cache file and folder structure. But it would still require additional information to let Olive know what the source is and its metadata (unless it's all embedded into each EXR).

I have mixed feeling about using a custom file extension. It makes it less clear what kind of file it is and double-click to open in standard app won't work unless we register `.ovexr`. A better approach might be to use `.olive-cache.exr` as extension. There's still the question whether the cache subfolders (`00`..`ff`) should be removed when clearing the cache, which complicates the cleanup procedure if we only want to remove folders which are empty after having deleted Olive's EXRs.

Another option would be to simply delete the entire mediacache folder and warn users if they change the cache path to an existing, non-empty folder. There would be no warning for the default cache path however.

**Comment by elsandosgrande** [comment]
I would personally go with prefixing the file name with `olive-editor-cache` or `olive-cache`, but I completely agree that changing the final file extension should be avoided.

@Simran-B If the cache is already stored in specific sub-directories, as opposed to simply being stored in the cache directory without any sub-directories, then wouldn't it be simple enough to delete all of the EXR files with the marker string and then delete all of the sub-directories that are left empty after that operation?

Regarding external tools, I'm guessing that they could be used on ingestion stations to generate the initial cache while copying the footage over to the local network-attached-storage server(s) after transcoding if that is necessary. As I don't have any experience in this field, this is what I think of when I think of an ingestion station: [reference one](https://linustechtips.com/topic/1039341-what-are-ingest-stations/), [reference two](https://www.youtube.com/watch?v=eQED3tF8wuw)

**Pull request closed without merging**
