### PR TITLE
Implement alt+click to reset to default value in SliderBase Issue #84

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
I've had ago at implementing this in a fairly simple way. I've added a default value that gets set in the constructor. If you Alt click a slider the value gets set to the default value. It doesn't work on sliders where the default is not the default set in SliderBase so I need to sort that. I just wanted to check I was going in the right direction.

Fixes sobotka/Olive#84

### CODE REVIEW

**Comment by itsmattkc** [comment]
This is essentially what I was looking to achieve, but I would do the `Qt::AltModifier` check in SliderLabel and emit a different signal like `emit ResetDefault()` if so (plus disable dragging).

**Comment by ThomasWilshaw** [comment]
There are two types of sliders, those that use the default value set in the SliderBase constructor (e.g. Position in the Orthographic Matrix node) and those that set a seperate default (e.g. Scale in the Orthographic Matrix node). This is causing issues; how do we know when to update the default value? The simplest way of fixing this I can think of is to find all the sliders that need an custom default set and explicitly call `SetDefaultValue()` with that value. Does that sound sensible? Or am I missing something?

**Comment by itsmattkc** [comment]
I think you're thinking of the NodeInput constructor, not the SliderBase constructor. The NodeInput default value doesn't change, therefore the NodeParamViewWidgetBridge is the class that would call SetDefaultValue() on the slider on init.

**Comment by ThomasWilshaw** [comment]
So in the NodeParamViewWidgetBridge CreateWidgets it woul be something like:

```
slider->SetDefault(input_->get_standard_value());
```

**Comment by ThomasWilshaw** [comment]
That seems to have worked. I think it's just a cas eof now finding all the places where sliders are used and settign there defaults.

**Comment by itsmattkc** [comment]
It would be `get_standard_value()` necessarily, I don't think there's actually access to the default values (one needs to be written in).

But yes, that's pretty much it. I'd say it's not even necessary to look for other sliders, those are the ones that matter the most.

**Comment by ThomasWilshaw** [comment]
Yes I had to use `get_split_standard_values()` for the multiple float sliders. There's a few like the colour picker and some of the settings in the export dialoge that need doing as they go to odd values when you Alt click on them. For example the dimensions of the exported video default to 1 when clicked, as opposed to the project dimensions (1920x1080 or whatever).

**Comment by itsmattkc** [comment]
If I were you, I'd do something like a `QVariant::isNull()` or a `bool` check to see if any default value has actually been set, and not bother setting to default if not since not all sliders are going to need a default value.

**Comment by ThomasWilshaw** [comment]
Sliders requiring defaults:
 -  ~~Nodes~~
 -  ~~Timeline~~
 -  Colour Picker
 -  Export Dialog Dimensions
 - ...

**Comment by ThomasWilshaw** [comment]
> 
> 
> If I were you, I'd do something like a `QVariant::isNull()` or a `bool` check to see if any default value has actually been set, and not bother setting to default if not since not all sliders are going to need a default value.

I'll give it  a go.

**Comment by sobotka** [comment]
Can you edit the subject to be more clear and add a link to the relevant issue? I would love to chase this but have no clue.

**Comment by ThomasWilshaw** [comment]
Linked PR to relevant issue.

**Comment by itsmattkc** [comment]
Out of those, I think the following _shouldn't_ have defaults:
- Timeline
- Color Picker
- Target Bit Rate
- Target File Size
- Any in Preferences (would probably be better to have a dedicated "reset to defaults" button somewhere)

Everything else is fine, and no others come to mind that need defaults.

**Comment by ThomasWilshaw** [comment]
Here's the final list of defaults:

 -  ~Nodes~ (What it's initialy set too or 0 if not)
 -  ~Export Dialog Dimensions~ (Defaults to Sequence width/height)
 -  ~Export Compression Settings~
           - ~Advanced (0)~
 - ~Speed/Duration~
        - ~Speed (100%)~
        -  ~Duration (clip length)~
 - Stream Properties Image sequence
       - ~Start Index~ (1)
       - ~End Index~ (sequence length)

All others ignore an Alt Click.

Needs cleaning up.

**Comment by ThomasWilshaw** [comment]
I've noticed the new gizmos don't update when we reset to the default value but I'm not sure how to fix that yet.

**Comment by itsmattkc** [comment]
I can look into gizmos. Is this ready to review and merge otherwise?

**Comment by ThomasWilshaw** [comment]
Thanks I not had a chance to get my head round them yet. Yes this is ready for review.

**Pull request merged**
