### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by XGSZZ**

### CODE REVIEW

**Comment by ThomasWilshaw** [comment]
Can you please description to this and let us know how complete it is?

**Comment by elsandosgrande** [comment]
@XGSZZ Could you please provide a description and say if the pull request is ready to be merged as-is?

**Comment by XGSZZ** [comment]
I just added and modified some Chinese characters in the zh_CN.Ts file. You can contrast the changes and then decide whether to merge this file. I’m sorry to trouble you.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sandy&amp;nbsp;Vujaković&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月21日(星期六) 凌晨1:01
收件人:&nbsp;&quot;olive-editor/olive&quot;<olive@noreply.github.com&gt;;
抄送:&nbsp;&quot;Sun&quot;<sun.zhizhou@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [olive-editor/olive] Translation (#1383)

**Comment by elsandosgrande** [comment]
@XGSZZ A description provides us with information which allows us to act more easily, knowing whether or not you intend to add more commits to the pull request before it gets merged for example. Just keep that in mind in the future.

**Comment by XGSZZ** [comment]
Got it. Thank you.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sandy&amp;nbsp;Vujaković&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月21日(星期六) 上午10:13
收件人:&nbsp;&quot;olive-editor/olive&quot;<olive@noreply.github.com&gt;;
抄送:&nbsp;&quot;Sun&quot;<sun.zhizhou@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [olive-editor/olive] Simplified Chinese Translation (#1383)

**Pull request merged**
