### PR TITLE
Crop and vignette Inverse Feature added

### PR DESCRIPTION
**Pull request by cgvirus**
response to:
https://github.com/olive-editor/olive/issues/789 &
https://github.com/olive-editor/olive/issues/881

### CODE REVIEW

**Comment by unfa** [comment]
The Crop effect inverts Alpha channel of the entire thing, not just the Crop result itself. I think the Crop's alpha should be calculated seaprately and multiplied with the incoming Alpha for a correct result.

Screenshot_20190503_173208
Screenshot_20190503_173226

In the above example Crop fights wiht the Chroma Key. I can work this around and get the expected result by applygin Crop first before Chroma Key:

Screenshot_20190503_173354

I'd be for fixing the Crop and adding a "Alpha Invert" effect (I guess alpha will always be between 0 and 1 even in scene-reffered model, right, @sobotka ?) so that should make sense fot the Color-Managed Pipieline too I guess?

What do you think?

**Comment by sobotka** [comment]
In an associated alpha encode, the RGBA should be convolved as one unit.

Regarding how alpha is combined / constructed, it would depend. There are technically more than a single case to deal with, depending on the underlying geometry assumptions. For example:
1. Geometry is correlated, or perfectly aligned. Imagine a triangle dividing the pixel in half, and another triangle perfectly snapping up against it.
2. Geometry is completely non-overlapping. Imagine the two triangles are present, but not overlapping.
3. Geometry is uncorrelated, arbitrary overlapping. The two triangles are overlapping.
4. Geometry is completely overlapping, and foreground is fully occluding.

This breaks down into variants of the generic over function `A + (1 - A) * B` or `A + B - A * B`. Nuke has several merge node math functions that describe the above situations via over, disjoint over, and conjoint over. In order, the alpha math works out to roughly, as best as I understand things:
1. `A + B`
2. `A + B`
3. `A + B - A * B`
4. `A`

Nuke’s disjoint:`if(a1+a2<=1, c2+c1, c2+c1*(1-a2)/a1)`
Nuke’s conjoint: `if(a2>a1, c2, c2+c1*(1 - a2/a1))`

Examples of correlated geometry would be a holdout matte, where you subtract a foreground object from a background element.

The generic over function is also the basic probability function.

00CF49CA-956C-434A-A5CA-DC27DE1073B1
F7CB23CA-3598-4479-8BD9-13F3C0FE4B67

**Comment by cgvirus** [comment]
Let me check it should not be too much hard to do. Will PR soon.

**Comment by cgvirus** [comment]
@unfa Let me know if it's fixed:
https://github.com/cgvirus/olive/blob/master/effects/shaders/crop.frag

PR: https://github.com/olive-editor/olive/pull/904

**Pull request merged**
