### PR TITLE
Update olive_es.ts

### PR DESCRIPTION
**Pull request by RafaMartorell**
I am a perfectionist and I observed that some words remained untranslated so I looked for lines of several ts files until I got a 100% translation in Spanish. I think that this ts file is the definitive one to have the Alpha version totally in Spanish.
The reason to change "es_ES" to "es" is because this translation is valid for any Spanish-speaking country and not only for Spain.
[olive_es.ts.zip](https://github.com/olive-editor/olive/files/3343106/olive_es.ts.zip)
A pleasure to collaborate with this project and excuse my lack of programming knowledge, I work in the audiovisual field.

### CODE REVIEW

**Comment by itsmattkc** [comment]
Thank you for this translation, I'll fold this into the 0.1.x code soon with all the other translations and make a release so they're accessible.

**Comment by RafaMartorell** [comment]
A pleasure to collaborate with this magnificent project, it was about time we had a free and professional free code video editor.

**Comment by RafaMartorell** [comment]
thank you, I think now it is correct to eliminate my fork for what it tells me here, I hope not to be wrong with this and forgive me being a newbie in this world of github

**Comment by Simran-B** [comment]
No worries, the changes are stored in the respective repository once a pull request is merged from a fork. The resulting commit does not depend on your fork in any way, so it is fine to delete the PR branch in your fork or to remove the entire fork from your account.

**Comment by RafaMartorell** [comment]
Thank you very much for your answer. Despite having a few years on GitHub they are a complete newbie :-)

**Pull request merged**
