### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
Almost all icons (except bold.svg because it can't be opened with inkscape) have been redesigned in accordance to the UI mock-up in this issue https://github.com/olive-editor/olive/issues/1006

### CODE REVIEW

**Comment by itsmattkc** [comment]
Don't worry, I'm not sure why bold.svg is broken but it was never used in the program. I think it was placed there for a feature that was never implemented.

**Comment by Fatih20** [comment]
Any inconsistencies on sizes of shapes or radii of round corners? Maybe the contrast between the button and the icon is not enough?  Any changes needed to be done?

**Comment by itsmattkc** [comment]
Sorry, looks like GitHub automatically closed this when I merged in the rewrite branch. I also can't re-open it, it looks like you'll have to re-open again against `master`.

Anyway, your icons are generally quite nice looking, however I've heard a few people concerned that some things (e.g. the arrows in the tool buttons) are harder to see or that the tool buttons in general are harder to decipher. I can give some specifics if you'd like.

**Comment by Fatih20** [comment]
Yes, please do give me specific.

**Pull request closed without merging**
