### PR TITLE
Extra Keying Effects I: Luma Key and Color Selector

### PR DESCRIPTION
**Pull request by oc1024**
I took a shot at partially implementing what I requested at #356 . This enables bloom (Color Selector + Blur + HSL) and amateur fire VFX.

This is my first attempt at GLSL code; I reused a lot of code from other effects and there is likely room for optimization/style changes.

### CODE REVIEW

**Comment by BrimsonBhin** [comment]
Works on `229d01a`. My only issue is that the min/max values are very sensitive. I would recommend scaling the thresholds from _**0-1**_ to  _**0-100**_, like the Chroma Key shader.

Nice work by the way

**Comment by oc1024** [comment]
@BrimsonBhin Implemented 0-100 scaling for this effect. As you said, makes it consistent with the Chroma Key effect and it is now possible to input values other than 0% and 100% with the mouse.

Also added an invert checkbox. Not very useful for most applications, but piping it between invert effects wasn't efficient.

**Comment by oc1024** [comment]
Olive's new blending mode infrastructure wants us to multiply RGB by A or else it'll overlay the colors instead. This commit will make the plugins compliant with this requirement, plus will allow the Color Finder shader to run on OpenGL 2.0.

**Comment by itsmattkc** [comment]
@oc1024 I was about to mention, this was broken by the new blending algorithm. Glad you were able to discover and fix that. I'll test it properly tomorrow and should merge shortly after.

**Pull request merged**
