### PR TITLE
0.1.x

### PR DESCRIPTION
**Pull request by w7390**
1. When a video is rendered, the audio seems to go faster than normal and ends before the video, and it is out of sync.

2. The Spanish language pack has no effect.

Greetings from El Salvador.

Nice Video Editor, Keep the good Work.

### CODE REVIEW

**Comment by w7390** [comment]
> 1. When a video is rendered, the audio seems to go faster than normal and ends before the video, and it is out of sync.
> 2. The Spanish language pack has no effect.
> 
> Greetings from El Salvador.
> 
> Nice Video Editor, Keep the good Work.

the audio is good when all the edit is linked, i have been testing that.

**Comment by etwleonelle** [comment]
I'm using Olive Video Editor to subtitle some videos into the Arabic language, I have an issue within the font because there are separations between letters as you know the Arabic language connects the letters (two cases of the letters separated letters and connected letters depend on the case of the letter positions in the sentence) I've attached picture of the issue
[https://ibb.co/crkY5Ym](url)

**Comment by John-stathakis** [comment]
I'm using the version in English and the first audio clip is sped up most of the time in the generated MP4 output, not in the preview in the app. To remedy the situation I have needed to change the speed to 95%

**Comment by John-stathakis** [comment]
Great video editor - thank you so much for making it available

**Pull request closed without merging**
