### PR TITLE
Add support for transitions when loading OTIO files

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
OTIO transitions are now added to the timeline as cross dissolves with
the appropriate in/out points,

Also added a safety check when dealing with media references.

### CODE REVIEW

**Review by elsandosgrande — APPROVED** [review]
This is working in my local builds (`tests/sample_data/clip_sample.otio` from the OpenTimelineIO repository does not result in any assertions being raised anymore), so I'd say that it's ready unless Thomas wants to add something.

**Comment by elsandosgrande** [comment]
@ThomasWilshaw Would you say that this is complete? I found it to function well in my review.

**Comment by ThomasWilshaw** [comment]
I think so yes

**Comment by elsandosgrande** [comment]
@itsmattkc

**Pull request merged**
