### PR TITLE
Tabbify Project Properties

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
As per @sobotka's suggestion I've tabbified the Project Properties. Are they any design guidlines that should be followed?
image

### CODE REVIEW

**Comment by itsmattkc** [comment]
I think I'd be inclined to just use QWidget instead of QFrame, but otherwise seems sane.

**Comment by ThomasWilshaw** [comment]
Will do. For the sake of consistency do you want the same done to Preferences?

**Comment by itsmattkc** [comment]
Tabs? No, it already used to be tabs, but we moved away from them because they become cumbersome with a lot of pages.

**Comment by ThomasWilshaw** [comment]
Changed QFrames to QWidget and squashed commits. Should be good to go.

**Comment by itsmattkc** [comment]
Merged in with 3da9643da2c142c6535dfb2cfbf4e68cc76aeeea (not sure why it didn't pick it up automatically)

**Pull request closed without merging**
