### PR TITLE
Rework timeline scrolling

### PR DESCRIPTION
**Pull request by mdmayfield**
This is an attempt to satisfy both mouse and touchpad use-cases, and multiple modifiers for axis swap:

- Mouse users usually want horizontal scrolling with the mouse wheel
- Touchpad users will want two-finger scrolling to move as expected, both horizontally and vertically
- Users accustomed to Qt will expect to use Alt/Option for axis swap
- Users accustomed to browsers and other apps expect Shift for axis swap
- Refactored the code a bit to be easier to read

With this patch, the mouse wheel will scroll horizontally if the pointer is within a section (audio vs video) of the timeline that doesn't have space to scroll vertically, or if that section is scrolled as far as it will go vertically in the direction the user is trying to scroll.

If there's room to scroll up or down, a mouse wheel will scroll vertically until it can't go further, after which it will scroll horizontally in the appropriate direction (up = left and down = right).

Two-finger scrolling on a touchpad works entirely as expected, with the exception that vertical two-finger scrolling behaves the same as mouse wheel scrolling (horizontal at ends of travel) as described above.

Either Shift or Alt can be used for axis swap.

As far as I could find, there is no straightforward way to tell the difference between scroll events sent from a physical mouse wheel vs. two-finger scrolling on a touchpad. If there is such a way, I'd recommend an approach using that instead of the behavior here.

Related to discussion in #549

### CODE REVIEW

**Comment by mdmayfield** [comment]
Updated this with a couple improvements:

1) Zoom was way too fast on touchpads because of ignoring the "120 distance = 1 click" convention in Qt.
2) Zoom in/out was asymmetrical (1.5 vs. 0.75); this should be 1.33 and 0.75, or 1.5 and 0.67. It seemed to feel nicer at 1.33 and 0.75, so used that as a base.
3) Took advantage of both Shift and Alt together [double-reversing the polarity](https://youtu.be/pIpl3VxttmM?t=18) to implement an "only scroll vertically, no horizontal shenanigans" option

**Comment by elsandosgrande** [comment]
I think the "scroll one way until impossible, then switch axis" is not very good, at least on a touchpad. I would suggest that behavior to be optional, while the no-auto-switch to be default.

**Comment by mdmayfield** [comment]
@elsandosgrande If there were a way to tell if the user had a touchpad or mouse, I would agree. But then there's the case of a touchpad *without* horizontal scrolling.

It's a very delicate task to try to satisfy all use cases here; there's a lot of different configurations possible.

One possibility might be a checkbox that would make the default behavior the same as if both Alt and Shift are held - vertical scrolls only scroll vertically, and horizontal scrolls only scroll horizontally, no matter what. If a mouse user had that checked they would be required to hold Shift or Alt to scroll horizontally (which might be OK with a lot of people).

**Comment by mdmayfield** [comment]
Gonna close this one for now - @elsandosgrande brings up some good points and I want to make sure that this is consistent with what I'm working on for the Graph Editor. Will open a new PR later.

**Pull request closed without merging**
