### PR TITLE
Switching from using CMake find modules to using OpenColorIO and OpenTimelineIO configuration files

### PR DESCRIPTION
**Pull request by elsandosgrande**
As I discovered by accident that OpenColorIO and OpenTimelineIO generate their own CMake configuration files when they're built and installed, I thought to utilise them. This is an attempt at that.

OpenColorIO seems to give a hissy fit on my laptop and OpenTimelineIO's `opentime` component doesn't seem to be detected, so this is incomplete, but nearly there. Completely clearing out the OpenColorIO and OpenTimelineIO directories and starting fresh doesn't do anything.

OpenColorIO issue:
```
FAILED: app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o 
/usr/lib/ccache/g++-11 -DAPPVERSION=\"0.2.0\" -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_OTIO -Iapp -I/home/sandy/Projects/Olive/source/app -Iapp/libolive-editor_autogen/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include/opentimelineio/deps -isystem /usr/include/OpenEXR -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -march=native -pipe -pthread -fuse-ld=bfd -Og -ggdb3 -fdebug-types-section -fasynchronous-unwind-tables -fstack-clash-protection -fstack-protector-strong -fno-plt -Wall -Wextra -fno-omit-frame-pointer -Wno-stringop-overflow -fdebug-prefix-map=/home/sandy=. -Werror -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++14 -MD -MT app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o -MF app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o.d -o app/CMakeFiles/libolive-editor.dir/codec/ffmpeg/ffmpegdecoder.cpp.o -c /home/sandy/Projects/Olive/source/app/codec/ffmpeg/ffmpegdecoder.cpp
In file included from /home/sandy/Projects/Olive/source/app/node/color/colormanager/colormanager.h:29,
                 from /home/sandy/Projects/Olive/source/app/node/project/project.h:28,
                 from /home/sandy/Projects/Olive/source/app/render/diskmanager.h:30,
                 from /home/sandy/Projects/Olive/source/app/codec/ffmpeg/ffmpegdecoder.cpp:47:
/home/sandy/Projects/Olive/source/app/render/colorprocessor.h:67:9: error: ‘ConstCPUProcessorRcPtr’ in namespace ‘OCIO’ does not name a type
   67 |   OCIO::ConstCPUProcessorRcPtr cpu_processor_;
      |         ^~~~~~~~~~~~~~~~~~~~~~
[48/377] /usr/lib/ccache/g++-11 -DAPPVERSION=\"0.2.0\" -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_OTIO -Iapp -I/home/sandy/Projects/Olive/source/app -Iapp/libolive-editor_autogen/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include/opentimelineio/deps -isystem /usr/include/OpenEXR -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -march=native -pipe -pthread -fuse-ld=bfd -Og -ggdb3 -fdebug-types-section -fasynchronous-unwind-tables -fstack-clash-protection -fstack-protector-strong -fno-plt -Wall -Wextra -fno-omit-frame-pointer -Wno-stringop-overflow -fdebug-prefix-map=/home/sandy=. -Werror -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++14 -MD -MT app/CMakeFiles/libolive-editor.dir/core.cpp.o -MF app/CMakeFiles/libolive-editor.dir/core.cpp.o.d -o app/CMakeFiles/libolive-editor.dir/core.cpp.o -c /home/sandy/Projects/Olive/source/app/core.cpp
FAILED: app/CMakeFiles/libolive-editor.dir/core.cpp.o 
/usr/lib/ccache/g++-11 -DAPPVERSION=\"0.2.0\" -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DUSE_OTIO -Iapp -I/home/sandy/Projects/Olive/source/app -Iapp/libolive-editor_autogen/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include -I/home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/include/opentimelineio/deps -isystem /usr/include/OpenEXR -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -march=native -pipe -pthread -fuse-ld=bfd -Og -ggdb3 -fdebug-types-section -fasynchronous-unwind-tables -fstack-clash-protection -fstack-protector-strong -fno-plt -Wall -Wextra -fno-omit-frame-pointer -Wno-stringop-overflow -fdebug-prefix-map=/home/sandy=. -Werror -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++14 -MD -MT app/CMakeFiles/libolive-editor.dir/core.cpp.o -MF app/CMakeFiles/libolive-editor.dir/core.cpp.o.d -o app/CMakeFiles/libolive-editor.dir/core.cpp.o -c /home/sandy/Projects/Olive/source/app/core.cpp
In file included from /home/sandy/Projects/Olive/source/app/node/color/colormanager/colormanager.h:29,
                 from /home/sandy/Projects/Olive/source/app/node/project/project.h:28,
                 from /home/sandy/Projects/Olive/source/app/core.h:32,
                 from /home/sandy/Projects/Olive/source/app/core.cpp:21:
/home/sandy/Projects/Olive/source/app/render/colorprocessor.h:67:9: error: ‘ConstCPUProcessorRcPtr’ in namespace ‘OCIO’ does not name a type
   67 |   OCIO::ConstCPUProcessorRcPtr cpu_processor_;
      |         ^~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

OpenTimelineIO issue:
```
CMake Warning at CMakeLists.txt:133 (find_package):
  Found package configuration file:

    /home/sandy/Projects/OpenTimelineIO/builds/g++-11/Og/install_dir/share/opentimelineio/OpenTimelineIOConfig.cmake

  but it set OpenTimelineIO_FOUND to FALSE so package "OpenTimelineIO" is
  considered to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  OTIO::opentime
```
Relevant OpenTimelineIO Slack discussion: https://academysoftwarefdn.slack.com/archives/CMQ9J4BQC/p1633120596127900

### CODE REVIEW

**Comment by itsmattkc** [comment]
I'm still not convinced this is a good idea, at least right now. In OpenImageIO's case at least, we specifically support the version that comes with Ubuntu 20.04 LTS, which doesn't have a CMake config. To drop the find script I believe would necessitate bumping the minimum OIIO version, for no real reason outside of just deleting our find script.

OCIO is a different story though because we use OCIO v2, which people will usually get the latest version of anyway since it can only be installed by using a rolling release or compiling manually.

**Comment by elsandosgrande** [comment]
@itsmattkc I didn't touch OpenImageIO, only OpenTimelineIO and OpenColorIO.

**Comment by itsmattkc** [comment]
My bad, I misread OpenTimelineIO as OpenImageIO. Carry on.

**Comment by elsandosgrande** [comment]
Apparently, the Windows and macOS runners failed to find OpenColorIO, with the Linux runners not showing any OpenColorIO issues. While I test out older GCC versions as well as Clang, @Simran-B, could you take a look at what's going on with the runners, since you seem to be mostly in charge of the Docker stuff?

**Comment by ThomasWilshaw** [comment]
Olive is about to undergo some largish code refactoring and I wanted to check on the status of old PRs before we do that. Do you olan to update/continue with the PR? Thanks

**Comment by elsandosgrande** [comment]
I'm knee-deep in learning Rust and C++ and studying for university, so this should definitely be resumed after the splintering. Also, given how long this has been untouched, it would probably be a good idea to start over either way 🥴

**Pull request closed without merging**
