### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by ZoomTen**
Adds support for `Bahasa Indonesia` in Olive.
You could probably ignore the commit that modifies `olive.pro`, I used it to test my translation.

Is the autosave dialog, etc. translatable now? Can't seem to find it when I updated my `ts` file.

### CODE REVIEW

**Comment by itsmattkc** [comment]
Thanks for the translation! Sorry, which auto-save dialog?

**Comment by ZoomTen** [comment]
@itsmattkc The one that shows up upon restarting after a crash, that says "Olive has found a recovery file, would you like to open it?"

There might be a couple of more things that have missing translatable strings

**Comment by itsmattkc** [comment]
@ZoomTen Strange, the string is wrapped in `tr()` here: https://github.com/olive-editor/olive/blob/master/global/global.cpp#L97

Maybe it doesn't like the fact that the string is split across two lines.

**Comment by ZoomTen** [comment]
@itsmattkc Ah, yeah. I checked my `ts` file again and I *did* translate it, my mistake.

It might also be that the locale hasn't been loaded by the time the message showed up, I use a custom stylesheet and the message showed up in the usual "Fusion" style.

**Pull request merged**
