### PR TITLE
Refactor/simplify the threadpool implementation for render tickets

### PR DESCRIPTION
**Pull request by aeroc7**

### CODE REVIEW

**Comment by itsmattkc** [comment]
Does this resolve #1899?

**Comment by aeroc7** [comment]
> Does this resolve #1899?

No, that's a separate issue.

**Comment by itsmattkc** [comment]
Understood. This looks good, my only concern is whether this might introduce race conditions related to RenderTickets. RenderTicket [emits a Qt signal](https://github.com/olive-editor/olive/blob/master/app/threading/threadticket.cpp#L127) when the job is finished, and when using QThreads, this signal is more or less guaranteed to be thread safe (if the sender and receiver are in different threads, Qt will queue the signal on the receiver's event loop so that the receiving function will run in the receiver object's thread, preventing race conditions). This was the purpose of the `ticket->moveToThread` calls. I'm wondering if without QThreads that will no longer be the case, and non-threadsafe receiver functions will now be run in other threads.

If this is the case, the easiest/simplest solution would be to add `Qt::QueuedConnection` to the signal connects, which would force the aforementioned event loop behavior. Otherwise if there's a non-Qt alternative, that could be worth exploring too.

**Comment by aeroc7** [comment]
> Understood. This looks good, my only concern is whether this might introduce race conditions related to RenderTickets. RenderTicket [emits a Qt signal](https://github.com/olive-editor/olive/blob/master/app/threading/threadticket.cpp#L127) when the job is finished, and when using QThreads, this signal is more or less guaranteed to be thread safe (if the sender and receiver are in different threads, Qt will queue the signal on the receiver's event loop so that the receiving function will run in the receiver object's thread, preventing race conditions). This was the purpose of the `ticket->moveToThread` calls. I'm wondering if without QThreads that will no longer be the case, and non-threadsafe receiver functions will now be run in other threads.
> 
> If this is the case, the easiest/simplest solution would be to add `Qt::QueuedConnection` to the signal connects, which would force the aforementioned event loop behavior. Otherwise if there's a non-Qt alternative, that could be worth exploring too. I'm not 100% sure if this is actually occurring or not at this time though.

Hm, I think it's fine, but I'm no Qt expert. Here's what I found:

> [...signal emission is thread-safe.](https://doc.qt.io/qt-5/threads-qobject.html#accessing-qobject-subclasses-from-other-threads)

And if I'm not mistaken, the only `connect` that is made to the thread ticket slot [Finished](https://github.com/olive-editor/olive/blob/0e3d6ef37429c6ab9cd3f29b906bd581a7e5f92a/app/threading/threadticket.h#L114) is in [threadticketwatcher.cpp](https://github.com/olive-editor/olive/blob/0e3d6ef37429c6ab9cd3f29b906bd581a7e5f92a/app/threading/threadticketwatcher.cpp#L48). There is no specified connection type in this call, so the default is [Qt::AutoConnection](https://doc.qt.io/qt-5/qt.html#ConnectionType-enum), which, according to the documentation, automatically determines if it can be a direct call or queued call (for thread safety).

`Qt::AutoConnection`
> (Default) If the receiver [lives in](https://doc.qt.io/qt-5/qobject.html#thread-affinity) the thread that emits the signal, Qt::DirectConnection is used. Otherwise, Qt::QueuedConnection is used. The connection type is determined when the signal is emitted.

**Comment by itsmattkc** [comment]
Yeah but I have a feeling that behavior relies on `QObject::thread()` which is set with `QObject::moveToThread`. See the notes on that same page:

> By default, a QObject lives in the thread in which it is created. An object's thread affinity can be queried using [thread](https://doc.qt.io/qt-5/qobject.html#thread)() and changed using [moveToThread](https://doc.qt.io/qt-5/qobject.html#moveToThread)().

> Note: If a QObject has no [thread](https://doc.qt.io/qt-5/qobject.html#thread) affinity (that is, if thread() returns zero), or if it lives in a thread that has no running event loop, then it cannot receive queued signals or posted events.

Is there a way to test which of these threads the receiver function is being called in? (in Qt it would be `QThread::currentThread` but I assume that wouldn't be applicable here)

**Comment by aeroc7** [comment]
> Yeah but I have a feeling that behavior relies on `QObject::thread()` which is set with `QObject::moveToThread`. See the notes on that same page:
> 
> > By default, a QObject lives in the thread in which it is created. An object's thread affinity can be queried using [thread](https://doc.qt.io/qt-5/qobject.html#thread)() and changed using [moveToThread](https://doc.qt.io/qt-5/qobject.html#moveToThread)().
> 
> > Note: If a QObject has no [thread](https://doc.qt.io/qt-5/qobject.html#thread) affinity (that is, if thread() returns zero), or if it lives in a thread that has no running event loop, then it cannot receive queued signals or posted events.
> 
> Is there a way to test which of these threads the receiver function is being called in? (in Qt it would be `QThread::currentThread` but I assume that wouldn't be applicable here)

After looking through the Qt source code, here's what I found:

The [thread id implementation](https://github.com/qt/qtbase/blob/f087e63bf585f51d6c530dd58a57155835e6df2c/src/corelib/thread/qthread.h#L187) is just a wrapper around the OS-specific method of getting the thread id. They seem to use some custom assembler, but an equivalent call, if using pthreads, would be `pthread_self()` (which they actually seem to fall back to on platforms they can't use assembler for anyways).

So it's not Qt-specific. In fact, all the calling system is doing is checking if the thread ids are the same, and in any case they aren't, it's a queued call. Seen [here](https://github.com/qt/qtbase/blob/a3f7dd5260d1855e637d4a616a82c96b4e4cc77c/src/corelib/kernel/qmetaobject.cpp#L1520).

However, it might be worth it, for clarity sake, to add an explicit `Qt::QueuedConnection` to the `connect` call.

**Comment by itsmattkc** [comment]
Ahh okay great, thanks for looking into that and confirming how that works. That was my only concern, so this should be good to merge

**Pull request merged**
