### PR TITLE
Build-files go into separate folders

### PR DESCRIPTION
**Pull request by jonno85uk**
I was looking into possibly assisting in this project and I wasn't keen on the filesystem-pollution when building the project.

### CODE REVIEW

**Comment by jonno85uk** [comment]
The olive-editor binary is now located in a different sub-folder so integration tests are failing.

**Comment by eszlari** [comment]
Why not simply build out of tree?

**Comment by jonno85uk** [comment]
As in create a build-dir and then ../qmake && make ?

**Comment by jonno85uk** [comment]
The pull request has gotten large so i'm closing.

I hope you can read this https://github.com/jonno85uk/olive/projects/2 as i'm going to continue on doing my thing whilst aligning with upstream because I like the program. However, I can't help but feel that if some of the accrued debt is tackled soon, this NLE will go the way of the rest.

**Pull request closed without merging**
