### PR TITLE
Alpha Fixed for Crop Invert

### PR DESCRIPTION
**Pull request by cgvirus**

### CODE REVIEW

**Comment by cgvirus** [comment]
response to https://github.com/olive-editor/olive/pull/880

**Comment by unfa** [comment]
It is better, but not perfect:

Screenshot_20190504_165206

Note the strange edge on the cropped side - that migth however be an issue of the Chroma Key.

**Comment by cgvirus** [comment]
Olive is currently broken finally. Let's wait for nodes to be processed for some days. I afraid it's the threshold of chroma key...But it has been fixed in nodes...So, no need to hack anymore.
I am closing this fix as conflict with new codes. Please save the file as back up if you need it urgently. Thanks.

**Comment by unfa** [comment]
Thanks! I'm gonna abstain from installing new version of Olive right now :D

**Pull request closed without merging**
