### PR TITLE
Attempt to fix the current Travis Linux build issue

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
I think this should fix the build issue but if the Travis build stiill fails I'll delete it.

### CODE REVIEW

**Comment by ThomasWilshaw** [comment]
Seems to build successfully on all the platforms now.

**Comment by itsmattkc** [comment]
I've tended to use `#include <cfloat>` to address this in the past. Perhaps using STL is better though?

To make things consistent, I'd say you should either use `<cfloat>` in this PR or change the others to `<limits>` as well (there are only two other source files where this should be necessary).

**Comment by ThomasWilshaw** [comment]
As far as I can tell there isn't much difference except that `<limits>` might be the more "proper" C++ way as it uses templates not macros (I could be completely wrong there though). That being said, `<limits>` just includes `<cfloat>` anyway (at least on Windows) so that seems a bit arbitary. I suppose `<cfloat>` is a bit more lightweight so I'll change it to that. I should really have checked what was already being done so sorry about that.

**Comment by itsmattkc** [comment]
Depends on the compiler. On MSVC for example, you don't need to `#include <memory>` for smart pointers, but you do on GCC. I think some compilers just include more standard headers by default.

**Comment by ThomasWilshaw** [comment]
Thanks, that's good to know.

**Pull request merged**
