### PR TITLE
Fix building without OTIO support

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
I saw there was already some support for building `otio` _without_ OTIO support so got it working on Windows at least (I've not yet attempted building OTIO myself...). I don't really know CMake very well so I might not have done it properly.

### CODE REVIEW

**Comment by Simran-B** [comment]
I don't see a need to add a new variable `OTIO_FOUND`. The `find_package(OpenTimelineIO)` call automatically sets `OpenTimelineIO_FOUND`. You can just use that can't you?

`if (OpenTimelineIO_FOUND)`

**Comment by ThomasWilshaw** [comment]
Ah okay, I got a bit confused with that. I'll update, thanks.

**Comment by Simran-B** [comment]
CMake does have a lot of magic behavior that surprises you. But what can you do.

**Comment by ThomasWilshaw** [comment]
Updated to use existing variable.

**Pull request merged**
