### PR TITLE
Filetype icon update? (dark palette)

### PR DESCRIPTION
**Pull request by ZoomTen**
I proposed earlier on the Discord that Olive could use its' own file type icon. Here's my take on an icon design. Might be related to #429.

Was considering making a pull request for the [light icons](https://github.com/ZoomTen/olive/commit/b24f3e580fa5c2c549afa5b3d831bf8f179c3d27), but I liked the dark ones more. You might want to [cherrypick](https://gist.github.com/ozh/cbce675ba35e0d336cff) this PR.

[Source svg](https://github.com/olive-editor/olive/files/3077688/mimetype_icons.zip), in case anyone wants to improve on it.

screenshot443
Large icon

screenshot442
In Olive's file selection box

(This PR only applies to Linux packaging, I haven't figured out how filetype icons work on Windows yet - perhaps they are embedded into the executable?)

### CODE REVIEW

**Comment by MrTeeXD** [comment]
These icons look amazing, i vote for this to be the project file icons

**Comment by BrimsonBhin** [comment]
Interesting. Currently, Windows just has a placeholder file icon for .ove files

**Comment by itsmattkc** [comment]
This looks good, however I actually think the light icon would be better. I personally think it looks more "professional" and would look less out of place on a dark theme than the dark icon would on a light theme.

**Comment by ZoomTen** [comment]
I added a separate pull request (#862) for the light version, if that's okay.

**Pull request closed without merging**
