### PR TITLE
[UI] update "New" icon with a right bottom triangle

### PR DESCRIPTION
**Pull request by pgilfernandez**
Update "new" icon with a right bottom triangle because the button really opens a menu and doesn't run a command.
This way it better fits the icon theme and how "Add tool" and "Transition tool" icons are designed.

Cheers

### CODE REVIEW

**Comment by philiplb** [comment]
I wonder how the Patreon Poll is going: https://www.patreon.com/posts/olive-icon-poll-29513786

**Comment by Simran-B** [comment]
@philiplb The poll ended Sep 4, 2019 with the most votes for the most abstract design. But this isn't related to the pull request at all. Also see https://github.com/olive-editor/olive/issues/1310#issuecomment-722954577

**Comment by pgilfernandez** [comment]
As @Simran-B says, it's not about a icon theme or logo but just about a simple triangle in the button.
The actual "add tool" and "Transition tool" icons have a little triangle at the bottom right of the icon for indication that, when the button is pressed, a dropdown menu will appear:
add-tool

The "new" button behaves the same way but has not this "triangle indicator":
new_old

This pull request tries to solve it like the following:
new_new

Does it make sense for you all?

**Review by Simran-B — APPROVED** [review]

**Comment by mamarilmanson** [comment]
Hello... suggestion: 

image

Click New Item on menu -> click corresponding number on keyboard... for faster clicks... 
Thoughts?

😃

**Pull request merged**
